### ISSUE TITLE
Atom feed XML is very large

### ISSUE THREAD

**Issue by Pastafarianist** [jakevdp/jakevdp.github.io#6]
Check out http://www.feedvalidator.org/check.cgi?url=http%3A%2F%2Fjakevdp.github.io%2Fatom.xml : it crashes saying that your feed breaks resource constraints. This makes it impossible to subscribe to your feed in Inoreader. Can you make it smaller?

**Comment by jakevdp** [comment]
Thanks – I know this is an issue, but I haven't had the time to track down the problem.

**Comment by jakevdp** [comment]
Should be fixed with the new build.
