### ISSUE TITLE
Question about your series on Bayesian vs Frequentist statistics.

### ISSUE THREAD

**Issue by codesuki** [jakevdp/jakevdp.github.io#7]
Sorry to hijack your GitHub issues for that. 
In https://jakevdp.github.io/blog/2014/06/06/frequentism-and-bayesianism-2-when-results-differ/ 
you are saying that Markov chains allow you to marginalize parameters.
Then you go on to extract some parameters from the chain. 
Does that mean: 'not looking at some parameter is marginalization'? 

I am not sure what exactly to google for here >_<
It would be great if you could point me in the right direction to learn more about the details.

Thank you for this great series of articles! They are very informative!

**Comment by jakevdp** [comment]
Yes, when looking at samples from a multi-dimensional distribution, ignoring a dimension is mathematically equivalent to marginalizing over it. It's one thing that makes MCMC quite convenient.

**Comment by codesuki** [comment]
Thanks for the fast answer!
I see, I will try to read up on markov chains again. I thought to marginalize we need to do integration / summation. 
MCMC really seems super convenient.

**Comment by jakevdp** [comment]
You do need to do integration, but MCMC is effectively a numerical integration via the sampling method. That's why ignoring a dimension is equivalent to integrating over it.

**Comment by codesuki** [comment]
Thanks again! That actually confirms some of my assumptions!
